# Generated by Django 4.2.7 on 2025-10-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleupload',
            name='raw_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
