# Generated by Django 4.2.7 on 2026-01-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_scheduler', '0002_scheduleupload_raw_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleupload',
            old_name='upload_date',
            new_name='uploaded_at',
        ),
        migrations.AlterUniqueTogether(
            name='operatingroom',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='actual_end',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='actual_start',
        ),
        migrations.AddField(
            model_name='surgery',
            name='cleaning_duration',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='surgery',
            name='is_prepped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='surgery',
            name='nurse_assigned',
            field=models.CharField(blank=True, default='待指派', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='operatingroom',
            name='number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='extracted_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='raw_text',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='uploaded_file',
            field=models.FileField(upload_to='schedules/'),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='status',
            field=models.CharField(choices=[('scheduled', '已排定'), ('in_progress', '手術中'), ('completed', '已完成')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_type',
            field=models.CharField(max_length=200),
        ),
        migrations.RemoveField(
            model_name='operatingroom',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='operatingroom',
            name='name',
        ),
        migrations.RemoveField(
            model_name='operatingroom',
            name='room_type',
        ),
    ]
