# Generated by Django 4.2.7 on 2026-01-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surgery_scheduler', '0003_rename_upload_date_scheduleupload_uploaded_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduleupload',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='scheduleupload',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='scheduleupload',
            name='raw_text',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='cleaning_duration',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='is_prepped',
        ),
        migrations.RemoveField(
            model_name='surgery',
            name='status',
        ),
        migrations.AddField(
            model_name='surgery',
            name='original_room',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='surgery',
            name='original_start_time',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='optimizedschedule',
            name='utilization_improvement',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='estimated_duration',
            field=models.IntegerField(default=90),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='nurse_assigned',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surgery',
            name='surgery_type',
            field=models.TextField(),
        ),
    ]
